exclude: (^.pixi/)
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        entry: detect-secrets-hook
        stages: [pre-commit, manual]
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json