[workspace]
authors = ["Lorenz Kort <lorenz.kort@gmail.com>"]
channels = ["conda-forge"]
name = "news-data"
platforms = ['linux-64', 'linux-aarch64', 'osx-64', 'osx-arm64', 'win-64']
version = "0.1.0"

[tasks]
postinstall = "spacy download nl_core_news_lg"
secrets = "detect-secrets scan . --baseline ../../security/.secrets.baseline --exclude-files '.*\\.secrets.baseline$' --exclude-files '.*/\\.pixi/.*' --exclude-files '.*/var/log/.*' --exclude-files '.*/node_modules/.*'"

[dependencies]
python = ">=3.13.11,<3.14"
pip = ">=25.3,<26"
sentence-transformers = ">=5.2.0,<6"
nbformat = ">=5.10.4,<6"

[pypi-dependencies]
# analyses
trafilatura = ">=2.0.0, <3"
newspaper3k = ">=0.2.8, <0.3"
selenium = ">=4.39.0, <5"

# Code Location Module
defs = {path = "./codelocation", editable = true}

# dagster
dagster = ">=1.12.7, <2"
dagster-webserver = ">=1.12.7, <2"
dagster-docker = ">=0.28.7, <0.29"
dagster-postgres = ">=0.28.7, <0.29"
dagster-polars = ">=0.27.8, <0.28"
dagster-slack = ">=0.28.12, <0.29"

# processing
feedparser = ">=6.0.12, <7"
pathlib = ">=1.0.1, <2"
ipykernel = ">=7.1.0, <8"
beautifulsoup4 = ">=4.14.3, <5"
lxml = ">=6.0.2, <7"
polars = ">=1.36.1, <2"
duckdb = ">=1.4.3, <2"
plotly = ">=6.5.0, <7"
pandas = "*"
types-psycopg2 = ">=2.9.21.20251012, <3"
protobuf = ">=6.33.2, <7"
spacy = "*"
pyarrow = "*"
networkx = "*"
pyvis = ">=0.3.2, <0.4"
anthropic = ">=0.75.0, <0.76"
pre-commit = ">=4.5.1, <5"
detect-secrets = ">=1.5.0, <2"
pyreadstat = ">=1.3.2, <2"
paramiko = ">=4.0.0, <5"
typer = ">=0.21.1, <0.22"
