[workspace]
authors = ["Lorenz Kort <lorenz.kort@gmail.com>"]
channels = ["conda-forge"]
name = "news-data"
platforms = ['linux-64', 'linux-aarch64', 'osx-64', 'osx-arm64', 'win-64']
version = "0.1.0"

[tasks]
postinstall = "spacy download nl_core_news_lg"
secrets = "detect-secrets scan . --baseline ../../security/.secrets.baseline --exclude-files '.*\\.secrets.baseline$' --exclude-files '.*/\\.pixi/.*' --exclude-files '.*/var/log/.*' --exclude-files '.*/node_modules/.*'"

[dependencies]
python = "<=3.12"
pip = "*"



[pypi-dependencies]
trafilatura = "*"
newspaper3k = "*"
selenium = "*"
nbformat = "*"
sentence-transformers = "*"

# Code Location Module
defs = {path = "./codelocation", editable = true}
dagster = "*"
dagster-webserver = "*"
dagster-docker = "*"
dagster-postgres = "*"
dagster-polars = "*"
dagster-slack = "*"
feedparser = "*"
pathlib = "*"
ipykernel = "*"
beautifulsoup4 = "*"
lxml = "*"
polars = "*"
duckdb = "*"
plotly = "*"
pandas = "*"
types-psycopg2 = "*"
protobuf = "*"
spacy = "*"
pyarrow = "*"
networkx = "*"
pyvis = "*"
anthropic = "*"
pre-commit = "*"
detect-secrets = "*"
pyreadstat = "*"
paramiko = "*"
typer = "*"
