[workspace]
authors = ["Lorenz Kort <lorenz.kort@gmail.com>"]
channels = ["conda-forge"]
name = "news-data"
platforms = ['linux-64', 'linux-aarch64', 'osx-64', 'osx-arm64', 'win-64']
version = "0.1.0"

[tasks]
postinstall = "spacy download nl_core_news_lg"
secrets = "detect-secrets scan . --baseline ../../security/.secrets.baseline --exclude-files '.*\\.secrets.baseline$' --exclude-files '.*/\\.pixi/.*' --exclude-files '.*/var/log/.*' --exclude-files '.*/node_modules/.*'"

[dependencies]
python = ">=3.14.3,<3.15"
pip = ">=26.0.1,<27"



[pypi-dependencies]
trafilatura = ">=2.0.0, <3"
newspaper3k = ">=0.2.8, <0.3"
selenium = ">=4.39.0, <5"
nbformat = ">=5.10.4,<6"
sentence-transformers = ">=5.2.2,<6"

# Code Location Module
defs = {path = "./codelocation", editable = true}
dagster = ">=1.12.14, <2"
dagster-webserver = ">=1.12.14, <2"
dagster-docker = ">=0.28.14, <0.29"
dagster-postgres = ">=0.28.14, <0.29"
dagster-polars = ">=0.27.9, <0.28"
dagster-slack = ">=0.28.14, <0.29"
feedparser = ">=6.0.12, <7"
pathlib = ">=1.0.1, <2"
ipykernel = ">=7.2.0, <8"
beautifulsoup4 = ">=4.14.3, <5"
lxml = ">=6.0.2, <7"
polars = ">=1.38.1, <2"
duckdb = ">=1.4.4, <2"
plotly = ">=6.5.2, <7"
pandas = "*"
types-psycopg2 = ">=2.9.21.20251012, <3"
protobuf = ">=6.33.5, <7"
spacy = ">=3.8.11, <4"
pyarrow = "*"
networkx = "*"
pyvis = ">=0.3.2, <0.4"
anthropic = ">=0.80.0, <0.81"
pre-commit = ">=4.5.1, <5"
detect-secrets = ">=1.5.0, <2"
pyreadstat = ">=1.3.3, <2"
paramiko = ">=4.0.0, <5"
typer = ">=0.24.0, <0.25"
